/* ════════════════════════════════════════════════════════════════════
 * B10 — Código sequencial nos cadastros
 *
 * Cada tabela de cadastro ganha uma coluna `codigo bigint` com IDENTITY,
 * pra exibir como ID amigável na UI. UUID continua sendo a PK interna.
 * ════════════════════════════════════════════════════════════════════ */

do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'produtos','produtores','clientes','locais','terminais',
    'transportadoras','motoristas','veiculos'
  ] loop
    -- 1. Adiciona coluna se não existe
    execute format('alter table public.%I add column if not exists codigo bigint', tbl);

    -- 2. Backfill: numera por id (ordenação estável e consistente)
    execute format($q$
      with numerados as (
        select id, row_number() over (order by id) as rn
        from public.%I
        where codigo is null
      )
      update public.%I t set codigo = n.rn from numerados n where t.id = n.id
    $q$, tbl, tbl);
  end loop;
end $$;

-- Adiciona IDENTITY + UNIQUE em cada tabela
do $$
declare
  tbl text;
  proximo bigint;
begin
  foreach tbl in array array[
    'produtos','produtores','clientes','locais','terminais',
    'transportadoras','motoristas','veiculos'
  ] loop
    execute format('select coalesce(max(codigo), 0) + 1 from public.%I', tbl) into proximo;
    begin
      execute format(
        'alter table public.%I alter column codigo add generated by default as identity (start with %s)',
        tbl, proximo
      );
    exception when others then
      null; -- já tem identity, pula
    end;
    execute format('alter table public.%I alter column codigo set not null', tbl);
    execute format('create unique index if not exists ix_%I_codigo on public.%I(codigo)', tbl, tbl);
  end loop;
end $$;
